# Environment parameters
env_name: PongNoFrameskip-v4 #   CartPole-v1 # LunarLander-v2 #  
atari: False

# Learning parameters
model: Apex-DQN
learner_device: cpu
worker_device: cpu
num_workers: 2
num_learners: 1
num_step: 3
batch_size: 512
max_episode_steps: None
param_update_interval: 50
max_num_updates: 100000 
tau: 0.01
learning_rate: 0.0001
gamma: 0.95
eps_greedy: 0.30
eps_decay: 0.95
gradient_clip: 10
q_regularization: 0.0
multiple_updates: 4

# Buffer parameters
buffer_max_size: 1000000 
use_per: True  
priority_alpha: 0.6
priority_beta: 0.4
priority_beta_start: 0.4 
priority_beta_end: 1.0 
worker_buffer_size: 1000

# Communication configs
pubsub_port: 5555
repreq_port: 5556
pullpush_port: 5557